### ISSUE TITLE
Analytics/logs or stats

### ISSUE THREAD

**Issue by fobetor** [bakerframework/bakercloud-ce-console#7]
Hello Andrew
 I need some informaton about the analytics.
I dont find an explanaition about what API INTERACTIONS in the tools tab refers to exactly. I cant see the Issue Downloads count... It is because my issues are free?
 In magrocket 1.0 , when I used it, in the log i can see when issues where downloaded. I imagine you disabled this log section because it make the log a little bit huge?.... 
 Is it a hug, or is it disbled ? Is there a way to re-enable it?
Thank you

**Comment by nin9creative** [comment]
API INTERACTIONS is the number of times the API methods are being called.  I thought it'd be useful to guage the activity happening between the Baker Application and the backend.  Kind of like a "hits" counter.

It should count downloads as well for free issues, but you must be using the Issue Security feature otherwise the API won't know when an issue was downloaded.  So if that is turned off then that's why you aren't seeing the tracking.  If it's turned on then I'm not sure what the issue might be.

**Comment by fobetor** [comment]
ah, you are correct, its disable because I disableinmagrocket due to some issue about security links... so in this version I didnt enabled it.
I'll try it 
Thanks

**Comment by fobetor** [comment]
Andrew... no, with security ON, I have the same problem as in magrocket whrn user tries to download:
onnection error when trying to download http://api.XXXXX.com/issue/DY2TER4P3S/04BBFF86-E733-4687-B6BC-DEE3C37E666D/CartoGrafia_Diciembre_2013?user_id=04BBFF86-E733-4687-B6BC-DEE3C37E666D&app_id=DY2TER4P44f&environment=debug: Cannot connect to api.XXXXX.com

I dont have the app in debug, but in production......

**Comment by nin9creative** [comment]
Well, if the request doesn't go through the API there is no way to track it.  I don't know why in your case the Issue Security isn't
working.  It should flow through if the Issues are free and allow them to be downloaded without an error...

The Analytics in the Backend really is just for high level info...  Since it's just tracking usage details at the API level it is probably
not the best approach for detailed information anyway.

I would suggest using the Baker Analytics API hooks to instead use something like Google Analytics or Count.ly etc if you want
deeper insights.

Andrew

**Comment by fobetor** [comment]
Well, I'll try to investigate why it does not work
Thank you

**Comment by fobetor** [comment]
Andrew, from your hel files
" with Issue Security turned on, the API does a lookup and validates that there is still an active subscription and/or the user has the appropriate rights to download the issue in question. "
Perhaps the security only works for Subscriptions?
Because I cant make it work when I turn it on

**Comment by nin9creative** [comment]
Yeah, but there is logic for Free Issues in there - maybe there is a bug for the Free Issues...  I'd have to check into it.

```
$app->get('/issue/:app_id/:user_id/:name', function ($app_id, $user_id, $name) use($app)
{
        global $dbContainer;
        $db = $dbContainer['db'];

        try {
                        $result = $db->prepare("SELECT * FROM ISSUES WHERE APP_ID = '$app_id' AND NAME = '$name' LIMIT 0,1");

                        $result->execute();
                        $issue = $result->fetch();

                        // The Issue is not found for App_ID and Name. Throw 404 not found error.
                        if (!$issue) {
                                header('HTTP/1.1 404 Not Found');
                                die();
                        }

                        // Retrieve issue Issue Product ID to cross check with purchases
                        $product_id = $issue['PRODUCT_ID'];

                        // Default to not allow download.                
                        $allow_download = false;

                        // Validate that the Product ID (from Issue Name) is an available download for given user                
                        if ($product_id) {
                                // Allow download if the issue is marked as purchased
                                $result = $db->query("SELECT COUNT(*) FROM PURCHASES
                                                                                                        WHERE APP_ID = '$app_id' AND USER_ID = '$user_id' AND PRODUCT_ID = '$product_id'");                

                                $allow_download = ($result->fetchColumn() > 0);
                        } else if ($issue['PRICING'] == 'free') {
                                // Issue is marked as free, allow download
                                $allow_download = true;
                        }

                        if ($allow_download) {

                                if((isInDevelopmentMode($app_id)=="TRUE") && !($app->request()->isHead())){logMessage(LogType::Info,"Downloading ISSUE: " . $name . " for APP ID: " . $app_id . " USER ID: " . $user_id);}

                                logAnalyticMetric(AnalyticType::ApiInteraction,1,NULL,$app_id,$user_id);
                                if(!($app->request()->isHead())){logAnalyticMetric(AnalyticType::Download,1,$name,$app_id,$user_id);}

                                // Redirect to the downloadable file, nothing else needed in API call
                                $app->response()->redirect($issue['URL'], 303);
                        }
                        else {
                                header('HTTP/1.1 403 Forbidden');
                                die();
                        }
                }
                catch(PDOException $e) {
                        // Handle exception
                        logMessage(LogType::Error, $e->getMessage());
                }
});
```

**Comment by fobetor** [comment]
Tomorrow i will check it too, but it sems that if a user is not registred for a subscription or purchase it does not allow download
 I will check too to se if i can help
Thanks

**Comment by nin9creative** [comment]
There may be a bug in the logic...  I can put it on the list of things I need to look into...

**Comment by fobetor** [comment]
Andrew, some more info:
I've been trying to see if there is a bug, but I cant detect it in the code.
I have looked the instalation, and my .htacces file is installed correctly, php version 5.3.27
What I have is an error from ¿my server?... once I make the call to the security url:
403 Forbidden
Now I'm lost... the final url is in an S3 bucket.. and without security Ihave no problems. I dont have more information about the 403 error in my server

**Comment by nin9creative** [comment]
Try using this code instead (I removed the code that checked that the user had rights to download the issue and instead just allow the download redirect - as well as log the analytic metric)

You should be able to just replace this function in the Index.php to test.

```
$app->get('/issue/:app_id/:user_id/:name', function ($app_id, $user_id, $name) use($app)
{
        global $dbContainer;
        $db = $dbContainer['db'];

        try {
                        $result = $db->prepare("SELECT * FROM ISSUES WHERE APP_ID = '$app_id' AND NAME = '$name' LIMIT 0,1");

                        $result->execute();
                        $issue = $result->fetch();

                        // The Issue is not found for App_ID and Name. Throw 404 not found error.
                        if (!$issue) {
                                header('HTTP/1.1 404 Not Found');
                                die();
                        }

                        if((isInDevelopmentMode($app_id)=="TRUE") && !($app->request()->isHead())){logMessage(LogType::Info,"Downloading ISSUE: " . $name . " for APP ID: " . $app_id . " USER ID: " . $user_id);}

                        logAnalyticMetric(AnalyticType::ApiInteraction,1,NULL,$app_id,$user_id);
                        if(!($app->request()->isHead())){logAnalyticMetric(AnalyticType::Download,1,$name,$app_id,$user_id);}

                        // Redirect to the downloadable file, nothing else needed in API call
                        $app->response()->redirect($issue['URL'], 303);
                }
                catch(PDOException $e) {
                        // Handle exception
                        logMessage(LogType::Error, $e->getMessage());
                }
});
```

**Comment by fobetor** [comment]
Hello Andrew
 I think I have reolved.... I'm not 100% confident since I have not tested with paid issue.
 The problem is solved changing
        if ($product_id && $issue['PRICING'] != 'free') {
adding the new condition in line 275
 This is due to the fact that the logic programmed first search for just $product_id is filled in the call, but t searches in PURCHASES, so first it encounters a product_id, but not in purchases.
 so the first condition is always met a the else if condition is not used in any case. 
 With the new condition,  My logic is that if an issue is free, it just can be always downladed.
if it's not free.. it have to be checked with purchases...
 I hope this helps to improve CE.
It is important because Google Stats and Apple Stats dont coincide........ so I'll like to know how many downloads I have...

**Comment by nin9creative** [comment]
I'll take a look.  I will admit that I didn't do a lot of testing with regards to the Free Issues bit because a lot of the work was
geared towards the paid stuff.  I will try your code and see, if it's good I'll commit it to the codebase.

Thanks for looking into this!

Andrew

**Comment by fobetor** [comment]
It normal Andrew. This is a lot of code and work well done. We are here to use it, test and contribute if possible

**Comment by bingimar** [comment]
I can testify that this change works. I was using the old MagRocket and changed line 241 from
<code>if ($product_id)</code>
to
<code>if ($product_id && $issue['PRICING'] != 'free') 
</code>

Used to get 403 error but managed to download a free issue that had a product_id.

Still not getting any logging though

**Comment by fobetor** [comment]
In magrocket i dont know, but in baker ce i have it correctly counting number of downloads

Enviado desde mi iPad

**Comment by bingimar** [comment]
Ok, I guess I'll have to upgrade, is the upgrade painless?

**Comment by nin9creative** [comment]
Have you already deployed an app?  There is no direct upgrade path.  Going forward there will be for the CE console...  Otherwise the easiest way is to reinstall with a blank DB.

Regards,
Andrew

**Comment by bingimar** [comment]
Yes its already in the App Store. I'll upgrade over the weekend I guess.

**Comment by nin9creative** [comment]
I pushed this change into the API master.
